MAX_SEQUENCE_LENGTH = 181
VALIDATION_SPLIT = 0.2
RATE_DROP_LSTM = 0.3
RATE_DROP_DENSE = 0.3
NUMBER_LSTM = 128
NUMBER_DENSE_UNITS = 64
ACTIVATION_FUNCTION = 'relu'
siamese_config = {
	'MAX_SEQUENCE_LENGTH' : MAX_SEQUENCE_LENGTH,
	'VALIDATION_SPLIT': VALIDATION_SPLIT,
	'RATE_DROP_LSTM': RATE_DROP_LSTM,
	'RATE_DROP_DENSE': RATE_DROP_DENSE,
	'NUMBER_LSTM': NUMBER_LSTM,
	'NUMBER_DENSE_UNITS': NUMBER_DENSE_UNITS,
	'ACTIVATION_FUNCTION': ACTIVATION_FUNCTION
}